work_dir: ./work_dir/recognition/ntu-xsub/test_HPGNetFusion-ensemble

# feeder
feeder: feeder.NTUDatasets.SimpleLoader
test_feeder_args:
  data_path: ./dataset/NTU-60/xsub/val_data.npy
  label_path: ./dataset/NTU-60/xsub/val_label.npy
  data_type: 'relative' 
  t_length: 200
  y_rotation: True
  displacement: 1
  sampling: 'resize'
  mmap: False

# model
sparse: True
model: net.HPGNet.ModelFusion
model2: net.HPGNet.ModelFusion

weights: "work_dir/recognition/ntu-xsub/HPGNetFusion/best_model.pt"
weights2: "work_dir/recognition/ntu-xsub/HPGNetFusion/best_model.pt"

model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  dilation: 1
  in_plane: 64
  topology: 'default'
  group_num: 5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'uniform'
    graph_type: 'undigraph'

# training
phase: 'test'
device: [0, 1]
test_batch_size: 128