# command line: main.py rec_stream --phase test --config config/mv-ignet/ntu-xview/train_hpgnet-complement_simple.yaml

base_lr: 0.2
batch_size: 128
config: config/mv-ignet/ntu-xview/train_hpgnet-complement_simple.yaml
debug: false
device:
- 0
- 1
eval_interval: 1
feeder: feeder.NTUDatasets.SimpleLoader
ignore_weights: []
log_interval: 100
model: net.HPGNet.ModelFusion
model_args:
    dilation: 1
    dropout: 0.3
    graph_args:
        graph_type: undigraph
        layout: ntu-rgb+d
        strategy: uniform
    group_num: 5
    in_channels: 3
    in_plane: 64
    num_class: 60
    topology: complement
nesterov: true
num_epoch: 90
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 1
save_log: true
save_result: false
show_topk:
- 1
- 5
sparse: false
start_epoch: 0
step:
- 30
- 50
- 70
test_batch_size: 128
test_feeder_args:
    data_path: ./dataset/NTU-60/xview/val_data.npy
    data_type: relative
    displacement: 1
    label_path: ./dataset/NTU-60/xview/val_label.npy
    mmap: false
    sampling: resize
    t_length: 200
    y_rotation: true
train_feeder_args:
    data_path: ./dataset/NTU-60/xview/train_data.npy
    data_type: relative
    displacement: 1
    label_path: ./dataset/NTU-60/xview/train_label.npy
    mmap: false
    sampling: resize
    t_length: 200
    y_rotation: true
use_gpu: false
weight_decay: 0.0001
weights: F:/mv-ignet/weights/xview/xview_HPGNet_epoch120_model.pt
work_dir: ./work_dir/recognition/ntu-xview/HPGNetFusion-complement
